version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_db
      MYSQL_USER: abdelilah
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

